---
- name: Download, Install and Configure PingCastle
  hosts: all
  gather_facts: true
  vars:
    ansible_user: ${option.winrm_user}
    ansible_password: ${option.winrm_password}
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: true
    ansible_winrm_transport: basic
    ansible_winrm_port: 5985
    tmp_directory: C:\tmp
    pingcastle_directory: C:\apps\pingcastle

  tasks:
  - name: Get download url from www.pingcastle.com
    win_shell: |
      get_url = (Invoke-WebRequest -Uri "https://www.pingcastle.com/download").Links.Href |select-string -pattern 'zip' | Sort-Object |Select-object -first 1
             Write-Host $get_url
    register: pwsh_output

  - name: Filter url result
    debug:
      msg: "{{ pwsh_output.host_out | regex_replace('[\\r\\n\\t]+','') }}"
    register: url_download_latest

  - name: Remove tmp directory
    win_file:
      path: "{{ item }}"
      state: absent
    with_items:
    - "{{ pingcastle_directory }}"
    - "{{ tmp_directory }}"

  - name: Create directory structure
    win_file:
      path: "{{ item }}"
      state: directory
    with_items:
    - "{{ pingcastle_directory }}"
    - "{{ tmp_directory }}"

  - name: Download the latest version of pingcastle
    win_get_url:
      url: "{{ url_download_latest }}"
      dest: "{{ tmp_directory }}"

  - name: Get all files in a folder
    win_shell: Dir -Recurse {{ tmp_directory }} | Get-Childitem | select -expandproperty name
    register: found_files
    ignore_errors: true

  - name: Filter and store only filename
    set_fact:
      latest_file: "{{ found_files.stdout_lines|list }}"

  - name: decompress the latest version of pingcastle
    win_unzip:
      src: '{{ tmp_directory }}\{{ latest_file }}'
      dest: "{{ pingcastle_directory }}"