---
- name: Pingcastle execution and report generation
  hosts: all
  gather_facts: True
  vars:
    ansible_user: ${option.winrm_user}
    ansible_password: ${option.winrm_password}
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: true
    ansible_winrm_transport: basic
    ansible_winrm_port: 5985
    pingcastle_directory: C:\apps\pingcastle
    report_directory: C:\apps\reports
    pingcastle_target: lab-purple.local

  tasks:
  - name: Get date of the day
    win_shell: Get-Date -Format "yyyyMMdd"
    register: get_date

  - name: Get the latest xml filename
    win_shell: |
       $latestfile = Get-ChildItem -path {{ report_directory }} -Attributes !Directory *.xml | Sort-Object -Descending -Property LastWriteTime | select -First 1
       $latestfile.Name
    register: latest_xml_report

  - name: Run pingcastle.exe to generate the report
    win_shell: |
       cd {{pingcastle_directory }}
       ./PingCastle.exe --healthcheck --datefile --server {{ pingcastle_target }}

  - name: Obtain information about file
    ansible.windows.win_stat:
      path: '{{ pingcastle_directory }}\{{ latest_xml_report }}'
    register: report_info

  - name: Move reports in another folder
    win_shell: Get-Item –Path {{ pingcastle_directory }}\ad_hc_{{ pingcastle_target }}_{{ get_date }}* | Move-Item -Destination {{ report_directory }}
    when: report_info.size > "1024"